str1 = 'Samsung_Galexy_S26_Ultra'
print("|> Name of the String: ", str1) # String Slicing
print("\t__Positive Indexing__")
print("\t\t1. |>> Start String at Posetive Index[1] & Ending Index[4]: ", str1[1:4])
print("\t\t2. |>> Start String at Negetive Index[-10] & Ending Index[-6]: ", str1[-10:-6]) # String Slicing
print("\t\t3. |>> Start String at Posetive Index[0] & Ending Index[7]: ", str1[0:7])
print("\t\t4. |>> Start String at Posetive Index[8] & Ending Index[14]: ", str1[8:14])
print("\t\t5. |>> Start String at Posetive Index[15] & Ending Index[18]: ", str1[15:18])
print("\t\t6. |>> Start String at Posetive Index[19] & Ending Index[24]: ", str1[19:24])
print("\t\t7. |>> Start String at Posetive Index[0] & Ending Index[1]: ", str1[0:1])
print("\t\t8. |>> Start String at Posetive Index[8] & Ending Index[9]: ", str1[8:9])
print("\t\t9. |>> Start String at Posetive Index[23] & Ending Index[24]: ", str1[23:24])
print("\t\t10. |>> Start String at Posetive Index[3] & Ending Index[6]: ", str1[3:6])
print("\t\t11. |>> Start String at Posetive Index[12] & Ending Index[17]: ", str1[12:17])
print("\t\t12. |>> Start String at Posetive Index[7] & Ending Index[8]: ", str1[7:8])
print("\n")
print("\t__Negetive Indexing__")
print("\t\t13. |>> Start String at Negetive Index[-5] & Ending Index[]: ", str1[-5:])
print("\t\t14. |>> Start String at Negetive Index[-10] & Ending Index[-6]: ", str1[-10:-6])
print("\t\t15. |>> Start String at Negetive Index[-15] & Ending Index[-11]: ", str1[-15:-11])
print("\t\t16. |>> Start String at Negetive Index[-20] & Ending Index[-16]: ", str1[-20:-16])
print("\t\t17. |>> Start String at Negetive Index[-25] & Ending Index[-21]: ", str1[-25:-21])
print("\t\t18. |>> Start String at Negetive Index[-9] & Ending Index[-6]: ", str1[-9:-6])
print("\t\t19. |>> Start String at Negetive Index[-16] & Ending Index[-10]: ", str1[-16:-10])
print("\t\t20. |>> Start String at Negetive Index[-24] & Ending Index[-17]: ", str1[-24:-17])
print("\t\t21. |>> Start String at Negetive Index[-5] & Ending Index[-1]: ", str1[-5:-1])
print("\t\t22. |>> Start String at Negetive Index[-12] & Ending Index[-9]: ", str1[-12:-9])
print("\t\t23. |>> Start String at Negetive Index[-20] & Ending Index[-15]: ", str1[-20:-15])
print("\t\t24. |>> Start String at Negetive Index[-6] & Ending Index[-5]: ", str1[-6:-5])
print("\t\t25. |>> Start String at Negetive Index[-18] & Ending Index[-13]: ", str1[-18:-13])
print("\n")
print("\t__Mixed Indexing__")
print("\t\t26. |>> Start String at Index[0] & Ending Index[-17]: ", str1[0:-17])
print("\t\t27. |>> Start String at Index[8] & Ending Index[-6]: ", str1[8:-6])
print("\t\t28. |>> Start String at Index[-5] & Ending Index[24]: ", str1[-5:24])
print("\t\t29. |>> Start String at Index[-16] & Ending Index[14]: ", str1[-16:14])
print("\t\t30. |>> Start String at Index[15] & Ending Index[-5]: ", str1[15:-5])
print("\t\t31. |>> Start String at Index[-18] & Ending Index[-9]: ", str1[-18:-9])
print("\t\t32. |>> Start String at Index[19] & Ending Index[-1]: ", str1[19:-1    ])
print("\t\t33. |>> Start String at Index[-24] & Ending Index[-7]: ", str1[-24:-7])
print("\t\t34. |>> Start String at Index[-23] & Ending Index[-9]: ", str1[-23:-9])
print("\t\t35. |>> Start String at Index[-15] & Ending Index[-4]: ", str1[-15:-4])
print("\t\t36. |>> Start String at Index[-10] & Ending Index[-9]: ", str1[-10:-9])
print("\t\t37. |>> Start String at Index[-7] & Ending Index[24]: ", str1[-7:24])
print("\t\t38. |>> Start String at Index[3] & Ending Index[10]`: ", str1[3:10])
print("\t\t39. |>> Start String at Index[-21] & Ending Index[-9]: ", str1[-21:-9])
print("\t\t40. |>> Start String at Index[-1] & Ending Index[23]: ", str1[-1:23])
print("\n")
print("\t__Blank Indexing__")
print("\t\t41. |>> Start String at Index[0] & Ending Index[]: ", str1[0:])
print("\t\t42. |>> Start String at Index[] & Ending Index[24]: ", str1[:24])
print("\t\t43. |>> Start String at Index[] & Ending Index[]: ", str1[:])
print("\t\t44. |>> Start String at Index[-24] & Ending Index[]: ", str1[-24:])
print("\t\t45. |>> Start String at Index[] & Ending Index[-1]: ", str1[:-1])
print("\t\t46. |>> Start String at Index[-24] & Ending Index[-1]: ", str1[-24:-1])
print("\t\t47. |>> Start String at Index[] & Ending Index[-6]: ", str1[:-6])
print("\t\t48. |>> Start String at Index[-7] & Ending Index[-6]: ", str1[-7:-6])
print("\t\t49. |>> Start String at Index[] & Ending Index[14]: ", str1[:14])
print("\t\t50. |>> Start String at Index[] & Ending Index[-16]: ", str1[:-16])
print("\n")